INSERT INTO master(id, name, addr) VALUES( 1,'炙り合鴨	'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_aigamo.png');
INSERT INTO master(id, name, addr) VALUES( 2,'炙りアナゴ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_anago.png');
INSERT INTO master(id, name, addr) VALUES( 3,'炙りえびチーズ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_ebi_cheese.png');
INSERT INTO master(id, name, addr) VALUES( 4,'炙りえびマヨ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_ebi_mayo.png');
INSERT INTO master(id, name, addr) VALUES( 5,'ゆず塩炙りはまち'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_hamachi.png');
INSERT INTO master(id, name, addr) VALUES( 6,'ゆず塩炙りほっき貝'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_hokkigai_h.png');
INSERT INTO master(id, name, addr) VALUES( 7,'炙りとろサーモン'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_salmon.png');
INSERT INTO master(id, name, addr) VALUES( 8,'炙りとろサーモンチーズ'	, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_salmon_cheese.png');
INSERT INTO master(id, name, addr) VALUES( 9,'炙りしめさば'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_shimesaba.png');
INSERT INTO master(id, name, addr) VALUES(10,'ゆず塩炙りとろはまち'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aburi_torohamachi.png');
INSERT INTO master(id, name, addr) VALUES(11,'合鴨'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aigamo.png');
INSERT INTO master(id, name, addr) VALUES(12,'合鴨オニオン'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aigamo_onion.png');
INSERT INTO master(id, name, addr) VALUES(13,'あじ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_aji.png');
INSERT INTO master(id, name, addr) VALUES(14,'赤にし貝'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_akanishigai.png');
INSERT INTO master(id, name, addr) VALUES(15,'甘えび'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_amaebi.png');
INSERT INTO master(id, name, addr) VALUES(16,'チーズハンバーグ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_cheese_hamburg.png');
INSERT INTO master(id, name, addr) VALUES(17,'特製漬けマグロ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_dukemaguro.png');
INSERT INTO master(id, name, addr) VALUES(18,'えび'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_ebi.png');
INSERT INTO master(id, name, addr) VALUES(19,'えびアボカド'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_ebi_abocad.png');
INSERT INTO master(id, name, addr) VALUES(20,'えび天'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_ebiten.png');
INSERT INTO master(id, name, addr) VALUES(21,'えんがわ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_engawa.png');
INSERT INTO master(id, name, addr) VALUES(22,'炭火焼牛カルビ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_gyukarubi.png');
INSERT INTO master(id, name, addr) VALUES(23,'炭火焼牛カルビマヨ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_gyukarubi_mayo.png');
INSERT INTO master(id, name, addr) VALUES(24,'炭火焼牛カルビユッケ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_gyukarubi_yukke.png');
INSERT INTO master(id, name, addr) VALUES(25,'活〆はまち'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_hamachi.png');
INSERT INTO master(id, name, addr) VALUES(26,'ハンバーグ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_hamburg.png');
INSERT INTO master(id, name, addr) VALUES(27,'ほっき貝'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_hokkigai_h.png');
INSERT INTO master(id, name, addr) VALUES(28,'いか天'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_ikaten.png');
INSERT INTO master(id, name, addr) VALUES(29,'いか天ガーリックマヨ'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_ikaten_garlicmayo.png');
INSERT INTO master(id, name, addr) VALUES(30,'ローストビーフ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_loastbeef.png');
INSERT INTO master(id, name, addr) VALUES(31,'ローストビーフ山わさび'	, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_loastbeef_yamawasabi.png');
INSERT INTO master(id, name, addr) VALUES(32,'まぐろ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_maguro.png');
INSERT INTO master(id, name, addr) VALUES(33,'まぐろはらみ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_maguroharami.png');
INSERT INTO master(id, name, addr) VALUES(34,'真いか'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_maika.png');
INSERT INTO master(id, name, addr) VALUES(35,'水だこ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_mizudako.png');
INSERT INTO master(id, name, addr) VALUES(36,'生えび'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_namaebi.png');
INSERT INTO master(id, name, addr) VALUES(37,'生えびユッケ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_namaebi_yukke.png');
INSERT INTO master(id, name, addr) VALUES(38,'ねぎとろ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_negitoro.png');
INSERT INTO master(id, name, addr) VALUES(39,'ねぎとろユッケ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_negitoro_yukke.png');
INSERT INTO master(id, name, addr) VALUES(40,'大葉水だこ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_oba_mizudako.png');
INSERT INTO master(id, name, addr) VALUES(41,'オニオンサーモン'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_onion_salmon.png');
INSERT INTO master(id, name, addr) VALUES(42,'大とろサーモン'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_otoro_salmon.png');
INSERT INTO master(id, name, addr) VALUES(43,'大とろサーモン山わさび'	, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_otoro_salmon_yamawasabi.png');
INSERT INTO master(id, name, addr) VALUES(45,'サーモン'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_salmon.png');
INSERT INTO master(id, name, addr) VALUES(46,'サーモンアボカド'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_salmon_avocad.png');
INSERT INTO master(id, name, addr) VALUES(47,'しめさば'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_shimesaba.png');
INSERT INTO master(id, name, addr) VALUES(48,'たらこ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_tarako.png');
INSERT INTO master(id, name, addr) VALUES(49,'たらマヨ'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_taramayo.png');
INSERT INTO master(id, name, addr) VALUES(50,'とろびんちょう'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_torobincho.png');
INSERT INTO master(id, name, addr) VALUES(51,'びんちょうマグロアボカド'	, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_torobincho_avocad.png.png');
INSERT INTO master(id, name, addr) VALUES(52,'とろびんちょう　山わさび'	, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_torobincho_yamawasabi.png');
INSERT INTO master(id, name, addr) VALUES(53,'とろいわし'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_toroiwashi.png');
INSERT INTO master(id, name, addr) VALUES(54,'つぶ貝'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_tsubugai.png');
INSERT INTO master(id, name, addr) VALUES(55,'旨だしたまご'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_umadashitamago.png');
INSERT INTO master(id, name, addr) VALUES(56,'わさびなす'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_wasabinasu.png');
INSERT INTO master(id, name, addr) VALUES(57,'焼きとろサーモン'		, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_yakitoro_salmon.png');
INSERT INTO master(id, name, addr) VALUES(58,'やりいか'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_yariika.png');
INSERT INTO master(id, name, addr) VALUES(59,'ゆず塩やりいか'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_yuzushio_yariika.png');
INSERT INTO master(id, name, addr) VALUES(60,'生ハム'				, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_namahamu.png');
INSERT INTO master(id, name, addr) VALUES(61,'生ハムユッケ'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_namahamu_onion.png');
INSERT INTO master(id, name, addr) VALUES(62,'活〆とろはまち'			, 'http://www.hamazushi.com/hamazushi/menu/images/nigiri/pho_toro_hamachi.png');



